# Базовый образ без GPU (используем стандартный Ubuntu 22.04)
FROM ubuntu:22.04

# Установка необходимых пакетов
WORKDIR /srv/jupyterhub

RUN apt-get update -y && \
    apt-get install -y python3-pip python3-venv nodejs npm && \
    pip3 install --no-cache-dir \
        jupyterhub \
        dockerspawner \
	jupyterhub-nativeauthenticator && \
    npm install -g configurable-http-proxy

# Копирование конфигурационного файла JupyterHub
COPY config/jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py

# Запуск JupyterHub с указанием конфигурационного файла
CMD ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]
