version: '3.8'

networks:
    storytech_network:
      name: storytech_network

services:
  jupyterhub:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Для управления Docker-контейнерами
      - ./config/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py  # Конфигурационный файл
      - jupyterhub_data:/srv/jupyterhub/data  # Общий том для данных
    ports:
      - "18220:8000"  # Порт для доступа к JupyterHub
    networks:
      - storytech_network
    restart: always  # Автоматический перезапуск при падении


volumes:
  jupyterhub_data:  # Том для хранения данных
