#prometheus.yml

scrape_configs:

  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'jupyterhub'
    metrics_path: '/hub/metrics'
    static_configs:
      - targets: ['jupyterhub:8000']

  - job_name: docker
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.

    static_configs:
      - targets: ["192.168.1.53:9323"]
