FROM nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04

WORKDIR /srv/jupyterhub

RUN apt-get update -y && \
    apt-get install -y python3-pip nodejs npm && \
    pip3 install --no-cache-dir \
        psycopg2-binary \
        dockerspawner \
        jupyterhub-nativeauthenticator \
        docker && \
    npm install -g configurable-http-proxy

COPY config/jupyterhub_config.py /srv/jupyter/jupyterhub_config.py

CMD ["jupyterhub", "-f", "/srv/jupyter/jupyterhub_config.py"]

